application: research-assistant
version: 1
runtime: python
api_version: 1

handlers:
- url: /AddFollow
  script: main.py
  
- url: /Search
  script: main.py
  
- url: /static
  static_dir: static

- url: /.*
  script: main.py
  login: required


