application: research-assistant
version: 1
runtime: python
api_version: 1

handlers:
- url: /addFollow/
  script: main.py
  login: required
  
- url: /static
  static_dir: static

- url: /.*
  script: main.py


